[package]
name = "src/forge-framework-v2"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Jest = "roblox/jest@3.20.0"
T = "osyrisrblx/t@3.1.1"
Trove = "sleitnick/trove@1.8.0"
Signal = "sleitnick/signal@2.0.3"
Bytenet = "ffrostflame/bytenet@0.4.6"
Promise = "evaera/promise@4.0.0"
Observers = "sleitnick/observers@1.0.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"